version: '3.9'
services:
 database:
   build:
    context: .
   hostname: database
   container_name: postgres
   restart: always
   ports:
     - "5432:5432"
   environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
   volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql