version: '3.9'
services:
 database:
   build: .
   hostname: database
   container_name: camagruDB
   restart: always
   ports:
     - "3306:3306"
   environment:
     - MYSQL_ROOT_PASSWORD=mdp
     - MYSQL_DATABASE=camagruDB
     - MYSQL_USER=test
     - MYSQL_ROOT_PASSOWRD=mdp
     - MYSQL_ALLOW_EMPTY_PASSWORD=yes
   volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql